const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';

export default { FETCH_DATA_PENDING, FETCH_DATA_SUCCESS, FETCH_DATA_ERROR };
