export const FETCH_DATA_PENDING = 'FETCH_DATA_PENDING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_COUNTRY_NAME = 'FETCH_COUNTRY_NAME';
export const CHANGE_FILTER = 'CHANGE_FILTER';
